//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS.Scada.ConsoleCRM.ServiceCRM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Site[] SitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Technician TechnicianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Site[] Sites {
            get {
                return this.SitesField;
            }
            set {
                if ((object.ReferenceEquals(this.SitesField, value) != true)) {
                    this.SitesField = value;
                    this.RaisePropertyChanged("Sites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Technician Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicianField, value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Technician[] TechniciansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Technician[] Technicians {
            get {
                return this.TechniciansField;
            }
            set {
                if ((object.ReferenceEquals(this.TechniciansField, value) != true)) {
                    this.TechniciansField = value;
                    this.RaisePropertyChanged("Technicians");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Technician", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class Technician : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TechnicianIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TechnicianID {
            get {
                return this.TechnicianIDField;
            }
            set {
                if ((this.TechnicianIDField.Equals(value) != true)) {
                    this.TechnicianIDField = value;
                    this.RaisePropertyChanged("TechnicianID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Measurement[] MeasurementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SiteIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Measurement[] Measurements {
            get {
                return this.MeasurementsField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementsField, value) != true)) {
                    this.MeasurementsField = value;
                    this.RaisePropertyChanged("Measurements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serialnumber {
            get {
                return this.SerialnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialnumberField, value) != true)) {
                    this.SerialnumberField = value;
                    this.RaisePropertyChanged("Serialnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Measurement", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class Measurement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MeasurementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.MeasurementTyp MeasurementTypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Site SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MeasurementID {
            get {
                return this.MeasurementIDField;
            }
            set {
                if ((this.MeasurementIDField.Equals(value) != true)) {
                    this.MeasurementIDField = value;
                    this.RaisePropertyChanged("MeasurementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.MeasurementTyp MeasurementTyp {
            get {
                return this.MeasurementTypField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementTypField, value) != true)) {
                    this.MeasurementTypField = value;
                    this.RaisePropertyChanged("MeasurementTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Site Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementTyp", Namespace="http://schemas.datacontract.org/2004/07/SKS.Scada.DAL")]
    [System.SerializableAttribute()]
    public partial class MeasurementTyp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MaximumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MeasurementTypIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKS.Scada.ConsoleCRM.ServiceCRM.Measurement[] MeasurementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MinimumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Maximum {
            get {
                return this.MaximumField;
            }
            set {
                if ((this.MaximumField.Equals(value) != true)) {
                    this.MaximumField = value;
                    this.RaisePropertyChanged("Maximum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MeasurementTypID {
            get {
                return this.MeasurementTypIDField;
            }
            set {
                if ((this.MeasurementTypIDField.Equals(value) != true)) {
                    this.MeasurementTypIDField = value;
                    this.RaisePropertyChanged("MeasurementTypID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKS.Scada.ConsoleCRM.ServiceCRM.Measurement[] Measurements {
            get {
                return this.MeasurementsField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementsField, value) != true)) {
                    this.MeasurementsField = value;
                    this.RaisePropertyChanged("Measurements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Minimum {
            get {
                return this.MinimumField;
            }
            set {
                if ((this.MinimumField.Equals(value) != true)) {
                    this.MinimumField = value;
                    this.RaisePropertyChanged("Minimum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCRM.IServiceCRM")]
    public interface IServiceCRM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCRM/AddSite", ReplyAction="http://tempuri.org/IServiceCRM/AddSiteResponse")]
        void AddSite(SKS.Scada.ConsoleCRM.ServiceCRM.Customer custom, string description, double longitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCRM/AddCustomer", ReplyAction="http://tempuri.org/IServiceCRM/AddCustomerResponse")]
        SKS.Scada.ConsoleCRM.ServiceCRM.Customer AddCustomer(string firstname, string email, string lastname, string password, string username, SKS.Scada.ConsoleCRM.ServiceCRM.Technician technician);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCRMChannel : SKS.Scada.ConsoleCRM.ServiceCRM.IServiceCRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCRMClient : System.ServiceModel.ClientBase<SKS.Scada.ConsoleCRM.ServiceCRM.IServiceCRM>, SKS.Scada.ConsoleCRM.ServiceCRM.IServiceCRM {
        
        public ServiceCRMClient() {
        }
        
        public ServiceCRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSite(SKS.Scada.ConsoleCRM.ServiceCRM.Customer custom, string description, double longitude, double latitude) {
            base.Channel.AddSite(custom, description, longitude, latitude);
        }
        
        public SKS.Scada.ConsoleCRM.ServiceCRM.Customer AddCustomer(string firstname, string email, string lastname, string password, string username, SKS.Scada.ConsoleCRM.ServiceCRM.Technician technician) {
            return base.Channel.AddCustomer(firstname, email, lastname, password, username, technician);
        }
    }
}
