//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anlage
    {
        public Anlage()
        {
            this.Messwerts = new HashSet<Messwert>();
        }
    
        public string AnlageSeriennummer { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Beschreibung { get; set; }
        public long AnlageID { get; set; }
    
        public virtual Kunde Kunde { get; set; }
        public virtual ICollection<Messwert> Messwerts { get; set; }
    }
}
