//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS.Scada.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public long MeasurementID { get; set; }
        public double Value { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual MeasurementTyp MeasurementTyp { get; set; }
    }
}
