//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messwert
    {
        public long MesswertID { get; set; }
        public double Wert { get; set; }
        public System.DateTime Zeitpunkt { get; set; }
    
        public virtual Anlage Anlage { get; set; }
        public virtual MesswertTyp MesswertTyp { get; set; }
    }
}
