//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Kundes = new HashSet<Kunde>();
            this.Technikers = new HashSet<Techniker>();
        }
    
        public long PersonID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Username { get; set; }
        public string Passwort { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Kunde> Kundes { get; set; }
        public virtual ICollection<Techniker> Technikers { get; set; }
    }
}
