//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS.Scada.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Measurements = new HashSet<Measurement>();
        }
    
        public string Serialnumber { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Description { get; set; }
        public long SiteID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Measurement> Measurements { get; set; }
    }
}
