//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS.Scada.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technican
    {
        public Technican()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public long TechnicanID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Person Person { get; set; }
    }
}
