//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Techniker
    {
        public Techniker()
        {
            this.Kundes = new HashSet<Kunde>();
        }
    
        public long TechnikerID { get; set; }
    
        public virtual ICollection<Kunde> Kundes { get; set; }
        public virtual Person Person { get; set; }
    }
}
